### ISSUE TITLE
Set default input parameters

### ISSUE THREAD

**Issue by jeanpsv** [betrybe/api-documentation-action#5]
```yml
    - uses: betrybe/api-documentation-action@v1
      with:
        owner: 'betrybe'
        repo: 'api-documentation'
        ref: 'main'
        token: ${{ secrets.MY_PAT }}
        targetOwner: 'betrybe'
        targetRepo: 'playbook'
        targetRef: 'master'
        targetWorkflowId: 'production.yml'
```

All parameters should have default values to make easy usage.
